[settings]
python.uv_venv_auto = "create|source"
experimental = true

[hooks]
postinstall = "hk install"

[env]
KUBECONFIG = "{{ config_root }}/kubeconfig"
TALOSCONFIG = "{{ config_root }}/talosconfig"
MINIJINJA_CONFIG_FILE = "{{ config_root }}/.github/.minijinja.toml"
HOMEBREW_BREWFILE = "{{ config_root }}/.github/Brewfile"
_.path = ['{{config_root}}/node_modules/.bin']

[oci.env]
KUBECONFIG = ""
TALOSCONFIG = ""
MINIJINJA_CONFIG_FILE = ""
HOMEBREW_BREWFILE = ""

[tools]
# https://docs.renovatebot.com/modules/manager/mise/#supported-default-registry-tool-short-names
uv = "0.12.10"
python = "3"
node = "24.20.0"

# Flux
"aqua:flux2" = "2.9.5"

# Kube
kubecolor = "0.7.1"
kubens = "0.11.0"
"aqua:CrunchyData/postgres-operator-client" = "0.5.3"
"aqua:kustomize" = "5.8.1"
"aqua:helm" = "4.2.4"
"github:helmfile/helmfile" = "1.7.4"
"aqua:derailed/k9s" = "0.51.0"
"aqua:stern/stern" = "1.34.0"

# Talos
"aqua:siderolabs/talos" = "1.14.0"

# Tools
"aqua:yq" = "4.53.6"
"aqua:jq" = "1.8.2"
"github:DopplerHQ/cli" = "3.76.5"
"cargo:minijinja-cli" = "2.24.0"
"github:gorcon/rcon-cli" = { version = "0.10.3", exe = "rcon" }
"github:slsa-framework/slsa-verifier" = "2.7.1"
"aqua:Orange-OpenSource/hurl" = "8.0.1"

# hk
"aqua:hk" = "1.57.0"
"aqua:pkl" = "0.32.1"
"aqua:ruff" = "0.16.6"
"npm:dclint" = "3.1.0"
"npm:renovate" = { version = "44.65.5", trust_policy_excludes = [
  "@yarnpkg/libzip",
] }
"aqua:actionlint" = "1.7.12"
"aqua:shellcheck" = "0.11.0"
rust = "1.98.1"
just = "1.58.0"
gum = "2.0.0"
"cargo:just-lsp" = "0.7.1"
rumdl = "0.2.65"
shfmt = "3.14.0"
popeye = "0.22.1"
crane = "0.22.1"
oxfmt = "latest"
