---
# yaml-language-server: $schema=https://crds.stevewm.dev/crds/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: github
  data:
    - secretKey: token
      remoteRef:
        key: GITHUB_HOMELAB_TOKEN

---
# yaml-language-server: $schema=https://crds.stevewm.dev/crds/notification.toolkit.fluxcd.io/provider_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-homelab
  namespace: flux-system
spec:
  type: github
  address: https://github.com/stevewm/homelab
  secretRef:
    name: github

---
# yaml-language-server: $schema=https://crds.stevewm.dev/crds/notification.toolkit.fluxcd.io/alert_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: github
spec:
  providerRef:
    name: github-homelab
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: cluster-core
    - kind: Kustomization
      name: cluster-apps
  exclusionList:
    - waiting.*socket
