# yaml-language-server: $schema=https://raw.githubusercontent.com/google/yamlfmt/refs/heads/main/schema.json
---
# https://github.com/google/yamlfmt/blob/main/docs/config-file.md
formatter:
  type: basic
  include_document_start: true
  include_document_end: false
  eof_newline: true
