---
game_version: "1.22.6"
mods_dir: /mods
mods:
  - id: primitivesurvival
    version: 5.0.6
  # - id: ExpandedFoods
  #   version: 1.7.4
  # - id: ACulinaryArtillery
  #   version: 1.2.5
  - id: CarryOn
    version: 1.14.2
  - id: BetterRuins
    version: 0.6.3
  - id: th3dungeon
    version: 1.0.1
  # - id: VintageRCon
  #   version: 1.0.0
  - id: webcartographer
    version: 0.11.2
  - id: pspeltpatch
    version: 0.0.2
  # - id: chiseltoolslite
  #   version: 1.15.1
  - name: vsexporter
    version: 1.0.6
