---
name: smartctl-exporter

services:
  smartctl-exporter:
    image: quay.io/prometheuscommunity/smartctl-exporter:v0.15.0@sha256:a76e08dbf5db4781fefd1ed81c65ad46ae8d2849dae6b6d3acebcde2fc4e59d6
    container_name: smartctl-exporter
    restart: always
    user: root
    ports:
      - '9633:9633/tcp'
    privileged: true
