# yaml-language-server: $schema=https://crds.stevewm.dev/crds/dragonflydb.io/dragonfly_v1alpha1.json
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: ${APP}-dragonfly
spec:
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.38.1@sha256:2351612e283141a9cc9779fb6065eacb2735241e0b8b83cefd537264c20cc60d
  replicas: 1
  args:
    - "--maxmemory=$(MAX_MEMORY)Mi"
    - "--proactor_threads=2"
    - "--cluster_mode=emulated"
  authentication:
    passwordFromSecret:
      name: ${APP}-dragonfly
      key: password

  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: "DoNotSchedule"
      labelSelector:
        matchLabels:
          app.kubernetes.io/part-of: ${APP}
          app.kubernetes.io/component: database
