# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/dragonflydb.io/dragonfly_v1alpha1.json
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: ${APP}-dragonfly
spec:
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.39.0@sha256:665ee58607d035881384be45b20025490ecf87069418f61f715c19117ed5fb7d
  replicas: 1
  args:
    - "--maxmemory=$(MAX_MEMORY)Mi"
    - "--proactor_threads=2"
    - "--cluster_mode=emulated"
  authentication:
    passwordFromSecret:
      name: ${APP}-dragonfly
      key: password

  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: "DoNotSchedule"
      labelSelector:
        matchLabels:
          app.kubernetes.io/part-of: ${APP}
          app.kubernetes.io/component: database
