---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tekton-operator
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/tektoncd/operator
  ref: # TODO: hope they publish to OCI registry eventually
    tag: v0.79.0
  ignore: |
    # exclude all
    /*
    # include helm chart
    !/charts/tekton-operator
