---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app renovate-operator
spec:
  interval: 30m
  maxHistory: 3
  chartRef:
    kind: OCIRepository
    name: renovate-operator
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: -1
  uninstall:
    keepHistory: false
  driftDetection:
    mode: warn
  values:
    fullnameOverride: *app

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi

    config:
      jobTTLSecondsAfterFinished: 86400 # 1 day

    rbac:
      ownNamespaceOnly: true

    # auth:
    #   oidc:
    #     enabled: true
    #     issuerUrl: https://sso.stevewm.dev
    #     clientId: renovate
    #     existingSecret: renovate-sso
    #     secretKey: client_secret

    route:
      enabled: true
      hostnames:
        - renovate.stevewm.dev
      parentRefs:
        - name: envoy-internal
          namespace: network

    webhook:
      enabled: true

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    dashboard:
      enabled: true
      grafanaDashboard:
        allowCrossNamespaceImport: true
        instanceSelector:
          matchLabels:
            grafana.internal/instance: grafana
