# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-internal-gateway
spec:
  endpointSelector:
    matchLabels:
      ingress.home.arpa/gateway: internal
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: network
            app.kubernetes.io/name: envoy
            gateway.networking.k8s.io/gateway-name: envoy-internal
