# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: "Build tools container"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .mise.toml
      - .github/workflows/push-tools-container.yaml

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

jobs:
  build:
    name: Build container
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/stevewm/tools
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          client-id: "${{ secrets.BOTTY_HILL_CLIENT_ID }}"
          private-key: "${{ secrets.BOTTY_HILL_PRIVATE_KEY }}"

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - run: crane auth login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"

      - run: echo "TAG=${{ env.IMAGE }}:$(date '+%Y-%m-%d-%H.%M.%S')" >> "$GITHUB_ENV"

      - name: Build and push container
        run: mise oci push --tool crane --no-mise "${{ env.TAG }}"

      - name: Clean up old images
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
        with:
          package-name: tools
          package-type: container
          min-versions-to-keep: 5
          delete-only-untagged-versions: "false"
